# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_raahi', '0002_auto_20160401_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='link',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
