# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_raahi', '0003_auto_20160401_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField()),
                ('journey_date', models.DateTimeField()),
                ('source', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('ticket_cost', models.IntegerField(default=0)),
                ('cash_back', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app_raahi.UserProfile')),
            ],
        ),
    ]
