# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 05:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_raahi', '0004_bookings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookings',
            new_name='UserBookings',
        ),
    ]
